[package]
name = "yarn-spinner"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
camino = "1.1.4"
prost = "0.11.8"
prost-types = "0.11.8"
thiserror = "1.0.39"

[build-dependencies]
prost-build = "0.11.8"
